version: '3.4'

services:
  jassoncodes:
    image: jassoncodes-fe
    container_name: fe-container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - "3000:80"